name: ArenaControl
main: com.github.Brianetta.ArenaControl.ArenaControl
version: 0.0.1
author: Brian Ronald
commands:
    arenacontrol:
        description: Controls arena floors by template
        aliases: [arenactl, actl]
        usage: |
            /arenacontrol assign <arena> <template>
            /arenacontrol arena list
            /arenacontrol arena define <name> <corner1> <corner2>
            /arenacontrol arena remove <name>
            /arenacontrol template list
            /arenacontrol template define <name> <corner1>
            /arenacontrol template remove <name>
            corners are in the numeric format: X Y Z
        permission: ArenaControl.arenacontrol
permissions:
    ArenaControl.*:
        description: Access to all ArenaControl commands
        children:
            ArenaControl.modify: true
            ArenaControl.apply: true
    ArenaControl.modify:
        default: op
    ArenaControl.apply:
        default: op
permission-message: Insufficient permissions